package Auxiliar;

public enum Tipos {
	
	VAR, NUMINT, NUMREAL, DEFVAR, SALTO, SE, TABREPARENTESES, TFECHAPARENTESES, OPSOMA,
	OPSUBTRAI, OPMULT, OPDIV, OPMODULO, OPLER, OPESCRE, INSTFIM, OPMAIOR, OPMENOR, OPIGUAL,
	OPATRIB, OPDIF, INICIO, FIM;

}
